//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int MaBienThe { get; set; }
        public int Stt { get; set; }
        public string HinhAnh1 { get; set; }
    
        public virtual BienThePhong BienThePhong { get; set; }
    }
}
