//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
        }
    
        public int MaPhong { get; set; }
        public string TenPhong { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<int> MaBienThe { get; set; }
    
        public virtual BienThePhong BienThePhong { get; set; }
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
    }
}
