//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhachSan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_KhachSanEntities1 : DbContext
    {
        public QL_KhachSanEntities1()
            : base("name=QL_KhachSanEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BienThePhong> BienThePhongs { get; set; }
        public DbSet<ChiTietHD> ChiTietHDs { get; set; }
        public DbSet<ChucVu> ChucVus { get; set; }
        public DbSet<HinhAnh> HinhAnhs { get; set; }
        public DbSet<HoaDon> HoaDons { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<Phong> Phongs { get; set; }
        public DbSet<TaiKhoanNV> TaiKhoanNVs { get; set; }
    }
}
