//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoanNV
    {
        public int MaTK { get; set; }
        public Nullable<int> MaNV { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
