//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan_LTW.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_KhachSanEntities : DbContext
    {
        public QL_KhachSanEntities()
            : base("name=QL_KhachSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BienThePhong> BienThePhong { get; set; }
        public DbSet<ChiTietHD> ChiTietHD { get; set; }
        public DbSet<ChucVu> ChucVu { get; set; }
        public DbSet<HinhAnh> HinhAnh { get; set; }
        public DbSet<HoaDon> HoaDon { get; set; }
        public DbSet<KhachHang> KhachHang { get; set; }
        public DbSet<LoaiPhong> LoaiPhong { get; set; }
        public DbSet<NhanVien> NhanVien { get; set; }
        public DbSet<Phong> Phong { get; set; }
        public DbSet<TaiKhoanNV> TaiKhoanNV { get; set; }
    }
}
