//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_KhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienThePhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienThePhong()
        {
            this.HinhAnhs = new HashSet<HinhAnh>();
            this.Phongs = new HashSet<Phong>();
        }
    
        public int MaBienThe { get; set; }
        public string BienThe { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
    
        public virtual LoaiPhong LoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HinhAnh> HinhAnhs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
